enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
# integrations-version = "v1.4.0-dev.1"
# patches-version = "v4.3.0-dev.1"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/AbakNacchan/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
version = "latest"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Permanent repeat'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
version = "latest"
included-patches = "'Enable slide to seek' 'Remove player controls background'"
excluded-patches = "'Custom branding name YouTube' 'Announcements' 'Enable debugging' 'Ambient mode switch'"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
arch = "arm64-v8a"
version = "latest"
